var windows__hal_8hpp =
[
    [ "WindowsPCAPNetworkInterface", "class_windows_p_c_a_p_network_interface.html", "class_windows_p_c_a_p_network_interface" ],
    [ "WindowsPCAPNetworkInterfaceFactory", "class_windows_p_c_a_p_network_interface_factory.html", "class_windows_p_c_a_p_network_interface_factory" ],
    [ "WindowsLock", "class_windows_lock.html", "class_windows_lock" ],
    [ "WindowsLockFactory", "class_windows_lock_factory.html", "class_windows_lock_factory" ],
    [ "WindowsCondition", "class_windows_condition.html", "class_windows_condition" ],
    [ "WindowsConditionFactory", "class_windows_condition_factory.html", "class_windows_condition_factory" ],
    [ "WindowsTimerQueueHandlerArg", "struct_windows_timer_queue_handler_arg.html", "struct_windows_timer_queue_handler_arg" ],
    [ "TimerQueue_t", "struct_timer_queue__t.html", "struct_timer_queue__t" ],
    [ "WindowsTimerQueue", "class_windows_timer_queue.html", "class_windows_timer_queue" ],
    [ "WindowsTimerQueueFactory", "class_windows_timer_queue_factory.html", "class_windows_timer_queue_factory" ],
    [ "WindowsTimer", "class_windows_timer.html", "class_windows_timer" ],
    [ "WindowsTimerFactory", "class_windows_timer_factory.html", "class_windows_timer_factory" ],
    [ "OSThreadArg", "struct_o_s_thread_arg.html", "struct_o_s_thread_arg" ],
    [ "WindowsThread", "class_windows_thread.html", "class_windows_thread" ],
    [ "WindowsThreadFactory", "class_windows_thread_factory.html", "class_windows_thread_factory" ],
    [ "WindowsWirelessTimestamper", "class_windows_wireless_timestamper.html", "class_windows_wireless_timestamper" ],
    [ "WindowsWirelessAdapter", "class_windows_wireless_adapter.html", "class_windows_wireless_adapter" ],
    [ "DeviceClockRateMapping", "struct_device_clock_rate_mapping.html", "struct_device_clock_rate_mapping" ],
    [ "WindowsEtherTimestamper", "class_windows_ether_timestamper.html", "class_windows_ether_timestamper" ],
    [ "WindowsNamedPipeIPC", "class_windows_named_pipe_i_p_c.html", "class_windows_named_pipe_i_p_c" ],
    [ "I217_DESC", "windows__hal_8hpp.html#aba35c455179c1d10726e29c84d147e1a", null ],
    [ "I219_DESC", "windows__hal_8hpp.html#a5018ed0fe5bdf80186cf9a03c6c76b07", null ],
    [ "NETWORK_CARD_ID_PREFIX", "windows__hal_8hpp.html#a363e7820ec07f2290febc53a3da51e5a", null ],
    [ "OID_INTEL_GET_RXSTAMP", "windows__hal_8hpp.html#ad4b6bad3efdf67de170fad274a68ba40", null ],
    [ "OID_INTEL_GET_SYSTIM", "windows__hal_8hpp.html#ae372f4cc7024263556f7c756b87fcc87", null ],
    [ "OID_INTEL_GET_TXSTAMP", "windows__hal_8hpp.html#abd559c9adf4f4f6e28887254eb31a779", null ],
    [ "OID_INTEL_SET_SYSTIM", "windows__hal_8hpp.html#ac2464725076c949c5613b8a71fd7ae8e", null ],
    [ "TimerArgList_t", "windows__hal_8hpp.html#a52f8033c0b50f46374156ec8180abde4", null ],
    [ "TimerQueueMap_t", "windows__hal_8hpp.html#a9697083f507a6e04711614c6703bea3e", null ],
    [ "OSThreadCallback", "windows__hal_8hpp.html#adba475057f1652394673ed488c9f1c01", null ],
    [ "WindowsTimerQueueHandler", "windows__hal_8hpp.html#a983f775bbf5e37456994318c0c8f37c8", null ],
    [ "WirelessTimestamperCallback", "windows__hal_8hpp.html#af2bed527a2a14e4a742ec5d88f75bb5f", null ],
    [ "DeviceClockRateMap", "windows__hal_8hpp.html#a279bd78690d5f4dc78890dc5e0a9564c", null ]
];